// Code generated by github.com/euank/ifacepropagate

package case01

import (
	"ifacepropogate.testcase/test01/pkg"
	"io"
)

func (r *ptrReadFrobulator) propogateInterfaces() io.Reader {
	_, ok0 := r.Reader.(pkg.Frobulator)
	switch {
	case ok0:
		return struct {
			io.Reader
			pkg.Frobulator
		}{r, r}
	case !ok0:
		return struct {
			io.Reader
		}{r}
	default:
		panic("unreachable")
	}
}
func (r *ptrReadFrobulator) Frobulate() {
	r.Reader.(pkg.Frobulator).Frobulate()
}
